export const wmoCodes: { [key: number]: string } = {
    0: "Clear sky",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Foggy", // "Fog",
    48: "Depositing rime fog",
    51: "Lightly Drizzling", // "Drizzle: Light intensity"
    53: "Moderately Drizzling", // "Drizzle: Moderate intensity",
    55: "Densely Drizzling", // "Drizzle: Dense intensity",
    56: "Lightly Freezing Drizzling", // "Freezing Drizzle: Light intensity",
    57: "Densely Freezing Drizzling", // "Freezing Drizzle: Dense intensity",
    61: "Slightly raining", // "Rain: Slight intensity",
    63: "Moderately raining",  // "Rain: Moderate intensity",
    65: "Heavily raining", // "Rain: Heavy intensity",
    66: "Lightly freezing raining", // "Freezing Rain: Light intensity",
    67: "Heavily freezing raining", // "Freezing Rain: Heavy intensity",
    71: "Slightly snowing", // "Snow fall: Slight intensity",
    73: "Moderately snowing", // "Snow fall: Moderate intensity",
    75: "Heavily snowing", // "Snow fall: Heavy intensity",
    77: "Snow grains",
    80: "Slightly rain showers", // "Rain showers: Slight intensity",
    81: "Moderately rain showers", // "Rain showers: Moderate intensity",
    82: "Violently rain showers", // "Rain showers: Violent intensity",
    85: "Slightly snow showers", // "Snow showers: Slight intensity",
    86: "Heavily snow showers", // "Snow showers: Heavy intensity",
    95: "Slightly thunderstorm", //  "Thunderstorm: Slight",
    96: "Slightly hail thunderstorm", // "Thunderstorm: Slight hail",
    99: "Heavily hail thunderstorm", // "Thunderstorm: Heavy hail",
};